### ISSUE TITLE
Icon request: icon-c

### ISSUE THREAD

**Issue by Berkmann18** [ForkAwesome/Fork-Awesome#101]
C is a really popular and important language, and having a proper font icon for it would be awesome.
![C](https://images.ecosia.org/FxIvrsRTJlJ9ksmBI7uYbNArRf4=/0x390/smart/https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2F3%2F35%2FThe_C_Programming_Language_logo.svg%2F1200px-The_C_Programming_Language_logo.svg.png)

**Comment by xuv** [comment]
Ok, I realize we have icons for some other languages such PHP and so on. But I've never seen an official icon for C.

Where did you find this image? Is it in any way official or recognized by the community as an official symbol for the C language?

**Comment by Berkmann18** [comment]
It's taken from the book on C by its creator (Denis Ritchie) and Brian Kernighan.
It's called "The C programming language".

**Comment by xuv** [comment]
Right, I guess then the 'C' could then be extracted to in its own icon...

**Comment by tessus** [comment]
I'm still not convinced that this is the official logo. e.g. look at all the O’Reilly Media books with their weird animals.
So unless I get an email from Brian Kernighan, I wouldn't use a trivial letter as an icon.
(I thought about emailing him, but it's rather embarrassing to bother him with this.)

Also please note that the shapes of the C on the original book and the second edition are slightly different.

**Comment by Berkmann18** [comment]
@tessus Is the O'Reilly Media books made by the language creators?
I don't think so and versions of C such as ANSI C uses the same sort of C as the icon.

The only difference I see is a slight change in the blue shade which wouldn't be relevant for a glyphicon.

**Comment by tessus** [comment]
@Berkmann18 
> Is the O'Reilly Media books made by the language creators?

Mostly not, I'd guess.

> The only difference I see is a slight change in the blue shade which wouldn't be relevant for a glyphicon.

Nope, that's why I said shape (not color). The C on the second edition cover, apart from the color and the obvious `Ansi C` tag, has a slightly wider arc on the left. The two ends of the C on the right side are parallel and also horizontal. Not so in the C on the cover of the first edition.

I was only saying that they are not the same, so which one should be the logo?

I'd go with the one from the first edition. But as I've mentioned before I'm not sure, if it's really the official logo. (Also most other books about C use different shapes of the letter C.) I don't have a problem with creating a logo for C.
Personally I would not want to create a new logo (any logo) with a letter, but that's just me. On the other side C is part of history and maybe in this case, the letter would make sense.

**Comment by tessus** [comment]
/ref https://upload.wikimedia.org/wikipedia/commons/3/35/The_C_Programming_Language_logo.svg

**Comment by Berkmann18** [comment]
I noticed that the CDN version is still at `v1.1.3` while the NPM one is at `v1.1.5`, is it normal or is it supposed to be linked?
