### ISSUE TITLE
Icon request: icon-spellcheck

### ISSUE THREAD

**Issue by beliys** [ForkAwesome/Fork-Awesome#122]
Hi there. This is a similar request as https://github.com/FortAwesome/Font-Awesome/issues/1373

**Comment by xuv** [comment]
I do like [the proposition made by @audis](https://github.com/FortAwesome/Font-Awesome/issues/1373#issuecomment-21875798) in that thread

**Comment by beliys** [comment]
Yeap, nice variant.

**Comment by Berkmann18** [comment]
+1

**Comment by justinboy71** [comment]
+1 Font Awesome needs a spell check icon!

**Comment by xuv** [comment]
Here is a proposition.
<img width="1147" alt="screen shot 2019-02-13 at 13 01 31" src="https://user-images.githubusercontent.com/192539/52733157-00feb780-2f90-11e9-8786-2bbef31c5668.png">

I've used `AZ` instead of `abc` to stay coherent with the Sorting icons:
https://forkawesome.github.io/Fork-Awesome/icon/sort-alpha-asc/

Let me know what you think.

**Comment by beliys** [comment]
Spellcheck icon are slightly different with sorting icons. For sorting icons for asc, we sort from A to Z and the arrow shows it and for desc it is the same, but the arrow shows from Z to A. For the spellcheck icon, abc is more familiar. But others may not agree with me.

**Comment by xuv** [comment]
@beliys Makes sense. Let me try something else then.

**Comment by xuv** [comment]
Here is a version with ABC.
<img width="1151" alt="screen shot 2019-02-14 at 14 38 11" src="https://user-images.githubusercontent.com/192539/52812758-41c90000-3066-11e9-955c-3730228ed3e5.png">

**Comment by beliys** [comment]
@xuv Good job. I like it!

**Comment by xuv** [comment]
Cool. I'll merge it then. It will be available in the next release
