### ISSUE TITLE
Icon request: icon-fdroid

### ISSUE THREAD

**Issue by Depau** [ForkAwesome/Fork-Awesome#135]
## Icon

Official colored icon: https://en.wikipedia.org/wiki/File:F-Droid_Logo_4.svg
Monochrome version I made (SVG): [fdroid-logo.zip](https://github.com/ForkAwesome/Fork-Awesome/files/2659877/fdroid-logo.zip)

## Name Suggestion

`f-droid` or `fdroid`

## Use Case

Most useful use case is links to app store, like for the Google Play logo.

**Comment by xuv** [comment]
Here is what it would look like:
![screen shot 2019-02-15 at 12 15 25](https://user-images.githubusercontent.com/192539/52872811-6df28880-311b-11e9-87e5-ecec1501058a.png)

Since we are making modifications to the official F-Droid logo and how it appears, I would like to have some feedback from the F-Droid project maintainers before merging this into master. If they don't approve these changes, we won't merge this into the set.

**Comment by Bubu** [comment]
The artwork is CC-BY-SA 3.0 as specified here: https://gitlab.com/fdroid/artwork/blob/master/fdroid-logo-2015/license.txt

So, yes, this is fine!

**Comment by xuv** [comment]
@Bubu Oh thanks for this. This is great.
