### ISSUE TITLE
Icon request: fa-torproject

### ISSUE THREAD

**Issue by imbsky** [ForkAwesome/Fork-Awesome#144]
## Icon

https://www.torproject.org/images/onion.jpg
https://www.torproject.org/docs/trademark-faq.html.en

## Name Suggestion

`torproject` or `tor`

## Use Case

https://www.torproject.org

**Comment by xuv** [comment]
@imbsky Thx for the submission. I like Tor, don't get me wrong. But what would be the use case for using the Tor icon in this icon set. Where do you plan to use the icon? Thx.

**Comment by imbsky** [comment]
Hi @xuv ,
For example, it would be useful if I want to add any information about my own Tor relay server to the website.

**Comment by xuv** [comment]
Thanks for linking to the Trademark FAQ. Although a big fan of Tor Project, when I read this: 
> Please don't modify the design or colors of the logo.

And when the logo has specific colors that prevent it to turn it into black and white, I'm tempted to not include it in the brand list in order to respect the will of the creators of the original project. 

I'm happy to add a generic onion icon though, as a vegetable, that can be used for many usages, such as to represent a Tor exit node for example,...

**Comment by imbsky** [comment]
I agree with you.

> I'm happy to add a generic onion icon though, as a vegetable, that can be used for many usages, such as to represent a Tor exit node for example,...

Oh, that's great.

**Comment by lucaspetter** [comment]
The Tor Project offers downloads of the logo on their [press/style guide](https://styleguide.torproject.org/visuals/#assets) for anyone to use, all licenced under Creative Commons Attribution 3.0. If you click the download link there to visit the [brand asset repo](https://github.com/TheTorProject/tor-media), they've included black and white SVGs of [the onion image](https://github.com/TheTorProject/tor-media/blob/master/Onion%20Icon/Black_Icon.svg) and a [circular onion image](https://github.com/TheTorProject/tor-media/blob/master/Onion%20Icon/Onion_Negative_Black_Background_Icon.svg), both of which are good for adding to Fork Awesome.

Since it turns out that neither design nor licencing are blockers for adding this logo to Fork Awesome, I'm making a PR for it.

---

Also related, the Tor Project has a [new icon](https://trac.torproject.org/projects/tor/attachment/ticket/25702/macos-stable.png) in the works for Tor Browser. This icon will replace the current [green globe](https://media.torproject.org/image/outdated/tor-browser-icon.png) app icon for Tor Browser while keeping the existing Tor Project brand logo. In other words, the app icon and brand logo are separate and the logo isn't changing. It's [been a year](https://trac.torproject.org/projects/tor/ticket/25702) and the new app icon still hasn't launched, but presumably it'll come soon and they'll release downloadable SVGs that we could add to Fork Awesome later if needed.
