### ISSUE TITLE
Ethereum icon is missing

### ISSUE THREAD

**Issue by htrob** [ForkAwesome/Fork-Awesome#17]
It's present in FontAwesome though.

https://fontawesome.com/icons/ethereum?style=brands

**Comment by xuv** [comment]
Fork Awesome is a fork of [Font Awesome 4.7](https://fontawesome.com/v4.7.0/icons/) which did not have an Ethereum icon.

**Comment by htrob** [comment]
@xuv Sorry, does this mean that it's not going to be added?

**Comment by xuv** [comment]
@htrob No problem. I think the intention behind this project is not to keep on par with Font Awesome. But to offer an alternative and a continuation of Font Awesome 4.7. Especially since the complete redraw and new direction Font Awesome has taken with 5.0.

Now, definitely, we can add an Ethereum icon if that would be useful to you. Though you should know that it will not have the same Unicode codepoint as Font Awesome. If that is ok with you.
