### ISSUE TITLE
Icon Requests: email-bulk

### ISSUE THREAD

**Issue by wioxjk** [ForkAwesome/Fork-Awesome#180]
# Icon

Email related icons

# Name suggestions
email-bulk
email-opened
email-send

# Use Case

Increase the options when it comes to email-related stuff.
Linking to mailing-lists or email-addresses.
Basically, the ones that is available here:
https://fontawesome.com/icons?d=gallery&q=email

**Comment by xuv** [comment]
@wioxjk Thanks for the suggestion. In regards to what you are proposing.
- [ ] email-bulk ( will rename this issue to `email-bulk` icon request if you don't mind then) 
- [x] email-opened (see [envelope-open](http://forkaweso.me/Fork-Awesome/icon/envelope-open/) and [envelope-open-o](http://forkaweso.me/Fork-Awesome/icon/envelope-open-o/)
- [x] email-send (see [send](http://forkaweso.me/Fork-Awesome/icon/paper-plane/) and [send-o](http://forkaweso.me/Fork-Awesome/icon/paper-plane-o/)

**Comment by wioxjk** [comment]
Thanks for your reply and for the clarification regarding the envelope-open(-o)

However, [send-o](http://forkaweso.me/Fork-Awesome/icon/paper-plane-o/) & [send](http://forkaweso.me/Fork-Awesome/icon/paper-plane/) could be very easily confused with [Telegram Messenger](https://telegram.org/) sadly.
I suggest, that the icon should be changed to distinguish it from Telegram, a suggestion would be to let it look more like the send icon in (roundcube)[https://proxy.duckduckgo.com/iu/?u=http%3A%2F%2Ffiles.digistar.vn%2Fimages%2Femail%20hosting%2Froundcube%2Fhinh3.png&f=1] or just make a new one called "send/send-on" and rename the current one to just "paper airplane".

**Comment by xuv** [comment]
@wioxjk Those `send` and `send-o` icons are already named `paperplane`. The `send` name is just an alias for the same icon. 

The roundcube icon you are referring to is also a paper airplane. I thought you were going to point to something different. But indeed, the paper plane is the classic choice for a "send message" or "send email" icon.

In that regard, I don't find Fork Awesome paper plane icon creating more confusion with Telegram than with any other messaging apps that would use a paper plane as a logo (and there are tons of them). 

It's the context that usually helps determine the meaning of these icons. The branding clash is not really a concern in this case because there are substantial differences with the Telegram icon, in regard to how paper planes icons are usually drawn.

**Comment by wioxjk** [comment]
Make sense, thanks for your time to explain your point :)
