### ISSUE TITLE
Icon Request: Discourse

### ISSUE THREAD

**Issue by mrdrogdrog** [ForkAwesome/Fork-Awesome#243]
## Icon

![Discourse](https://user-images.githubusercontent.com/6124140/83887594-f4840c80-a748-11ea-8e94-a6805450b92f.png)

## Name Suggestion

Discourse

## Use Case

Discourse is a self host discussion platform. We want to link to a discourse instance and use an icon for that.

**Comment by xuv** [comment]
Is there any single color version fo the logo. Something that we could use as an icon? 
I can't seem to find anything like this. 

In order to introduce this logo in the set, we need a version of it that exists in one color only. No gradient, no shades. All black for example.

The only thing I found is this: https://github.com/discourse/discourse/blob/fdfb7ed7648ace1f3fe228db2567976363cb103f/app/assets/images/logo-single-dev.png

But that does not work.

**Comment by mrdrogdrog** [comment]
![IMG_20200607_130003](https://user-images.githubusercontent.com/6124140/83967151-3b940e00-a8bf-11ea-8cfc-fdbc48acb82b.jpg)

What about this? This is how font awesome solved the problem.

**Comment by xuv** [comment]
Sounds good to me.

**Comment by Hugo-Trentesaux** [comment]
When will it be merged?
