### ISSUE TITLE
local() section in CSS

### ISSUE THREAD

**Issue by grigorii-horos** [ForkAwesome/Fork-Awesome#251]
I found that `@font-face` doesn't contain `local()` section. I understand that the probability that this font is installed is very small, but this will be very useful for users which did this.

**Comment by xuv** [comment]
Good suggestion. Thank you for making it.

I have concerns about this. But it might be my lack of knowledge on the topic. But what happens if the local version is anterior to the one used by the website. Let’s say the site would use the latest version of the font and some of those characters don’t exist in the previous version of the font that the visitor has currently installed locally. What happens in those cases? Is the remote version used for the missing characters? Or are they just not displayed because the browser takes the local font first and ignores the remote one?

Anybody knows exactly how this would work?

**Comment by grigorii-horos** [comment]
@xuv Browser will use local version. But I think you don’t need to worry about this. If user installed this font it means that this user is hard skilled. Or this font can be installed with some package managers, and updated by them.

**Comment by xuv** [comment]
@grigorii-horos that’s a very bold assumption about users of the font. I’m not sure so many people are aware of versioning, package managers and the importance of having your local fonts in sync with font releases.

**Comment by grigorii-horos** [comment]
@xuv I’m not sure so many people are aware of possibility to install this font locally
