### ISSUE TITLE
CDN?

### ISSUE THREAD

**Issue by xuv** [ForkAwesome/Fork-Awesome#32]
Since some people seem to want to want a CDN for distribution. Press the 👍 if that is your case.

In the mean time, I've tried to set it up with [jsDelivr](https://www.jsdelivr.com/package/npm/fork-awesome)... But I'm definitely sure I got the paths all wrong...

If one of you want to tackle this issue or make suggestions on how to improve this.

**Comment by MartinKolarik** [comment]
Hi @xuv, Martin from jsDelivr here.

The "default file" option allows you to access one file with a shorter URL, in your case that would be https://cdn.jsdelivr.net/npm/fork-awesome@1.0.8 and we show that file at the top of the list. However, it doesn't work well with CSS which uses relative paths to import other files. In this case I recommend you simply use the full link https://cdn.jsdelivr.net/npm/fork-awesome@1.0.8/css/fork-awesome.min.css which should work without any problems.

**Comment by xuv** [comment]
@MartinKolarik Ok, great. Thx for the tip. One thing that I have not figured out with CDNs yet is what happens with the relative paths inside the CSS file. Those paths in this case point to `../fonts` folder. Will it work out of the box finding those fonts or should they use absolute path?

**Comment by tessus** [comment]
@xuv I'm a bit confused. The CDN link says 1.0.8, yet there's no 1.0.8 release in this repo.

I wanted to create a subresource integrity hash, but without the release, I don't know which file (from which git hash) I should use. (It obviously makes no sense to create it from the CDN. ;-))

It would be great, if you could provide links like so:

`<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fork-awesome@1.0.8/css/fork-awesome.min.css" integrity="sha384-HASH-HERE" crossorigin="anonymous">`

**Comment by xuv** [comment]
@tessus Sorry. Forgot to push the latest tags in this repo. It;s now done.

Here is the link with the integrity check:
`<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fork-awesome@1.0.8/css/fork-awesome.min.css" integrity="sha256-d2k91UoAYBI3jOWCbanz+cTk+fxLAkSVLvxrHo6xvy8=" crossorigin="anonymous">`

**Comment by tessus** [comment]
@xuv great. thank you. btw, I meant you might want to provide these links on the web site in the section 'Get Started' in a subsection 'Using CDN'.
I'm not a web designer, but I think I should be able to add such a section to the gh-pages branch.

I'm gonna change my web site when I get up tomorrow. I just came home 2 hours ago and I definitely need my beauty sleep. :-)

**Comment by xuv** [comment]
@tessus Yes. Good idea to add this the 'Get Started' page. I'll add you as a contributor so you can push new branches into this repo.

**Comment by tessus** [comment]
Thanks. It looks like the entire web site is static. This means that it has to be updated every time there's a new release.
Is there a way to use some sort of dynamic content? I use JS to at least show and download the latest available package without having to update the [web site](http://tessus.github.io/mod_authnz_ibmdb2/).

see: https://github.com/tessus/mod_authnz_ibmdb2/blob/gh-pages/index.html#L17-L37

Here are a few questions: 

- why is the zip file located in the assets directory of the web site?
Wouldn't it make more sense to add this binary to the corresponding [release](https://github.com/ForkAwesome/Fork-Awesome/releases) ?
- is there a way to create dynamic content (e.g. the SRI hash) for a release? (otherwise the web site has to be updated every time there's a release)

I create the SRI hash with openssl on the command line, but I doubt we have access to PHP or server side openssl to get something like this done on the github web site. So what's the best approach to handle this?
Is it possible to add the SRI hash to a file in the repo and read that file with JS?

**Comment by tessus** [comment]
@MartinKolarik Is there a reason why we shouldn't use a jsDelivr link that looks like this:

`https://cdn.jsdelivr.net/gh/ForkAwesome/Fork-Awesome@1.0.8/css/fork-awesome.min.css` 

In this case the npm package does not have to be updated and only a release has to be created in the github project, correct?

**Comment by xuv** [comment]
@tessus: I think the generation of a npm package has a larger goal that just for serving the jsDelider CDN. Some people might want to include the files in their JS project without requiring to use a CDN. And that might be an easy way to do so in whatever JS based app they would be building.

**Comment by tessus** [comment]
@xuv I see. that makes sense. I just wanted to understand the differences.

**Comment by xuv** [comment]
@tessus: You're right. jsDelivr does not require using npm (I saw that today only). And we could just have all releases being pulled from Github. But since npm is being updated anyway... maybe it's okay to keep it like this for the moment. Unless you have a better proposition.

**Comment by tessus** [comment]
@xuv I'm not really a web guy, so I did not even think about npm in the first place. I'm sure the npm package has its advantages. as long as npm is updated every time you make a new release on github, everything will be fine. I just had this out-of-sync problem in my head that made me question the reasoning behind it.

so basically there are 3 things that have to be done manually when a new release is created:

1. create release zip file
2. update npm
3. update web site

I like to automate these things. That's all.

**Comment by xuv** [comment]
@tessus:
 - The zip file is automatically built when the website is updated. But since you pointed it out, we could skip that part because Github serves .zip for releases. 
 - Publishing to npm is really easy. It only requires one command: `npm publish` 
 
So indeed, we could add this one liner in the package.json script list under "deploy": 
`git push --tags && npm publish && jgd -n` and that would be all done.

But you would need to have all the permissions necessary on all branches and npmjs site to

**Comment by tessus** [comment]
@xuv ah, ok. see, I thought you had to create the zip file manually. that's why I suggested to use either the zip file created by the release or to add the zip file to the release and use JS to retrieve the version  info and file name on the web site. but your process already does all that.

here are our 2 approaches:

- yours: trigger the web site build -> web site is generated with all the correct version numbers
- mine: create a release -> no need to trigger a web site build (web site picks up version numbers and filenames from the release)

After thinking about it, your approach is better, since new versions also might require a change of the documentation and so on. My approach only works, if the web site is pretty much static except the version number and download link for the latest version.

(I'm sorry that parts of this ticket are off-topic, but I couldn't find your email in your gh profle. I'd rather do this kind of discussion via email.)

**Comment by xuv** [comment]
@tessus: no worries. I still think you brought up a good point regarding the zip file. Even if it's automated, there is no real point in zipping it ourselves if a Github release mechanism already does it. It will also make the `gh-pages` branch a little lighter.

As for the discussion, I don't mind having this in the issues of GH. I know some software dev projects don't like this. But it's a design repo here. Designers are very chatty people anyway. ;-)

We should have some general discussion forum somewhere. I believe that's why Github created this [team pages](/ForkAwesome/teams/contributors) if you prefer to use that.

**Comment by MartinKolarik** [comment]
@tessus no, you can use the GitHub-based links too if that's easier for you.

**Comment by xuv** [comment]
73039c316ef1ebbf79e32bf475390a8f1f12df57 adds the CDN Link in the documentation, thx to @tessus.
