### ISSUE TITLE
web site questions

### ISSUE THREAD

**Issue by tessus** [ForkAwesome/Fork-Awesome#38]
It looks like the entire web site is static. This means that it has to be updated every time there's a new release.
Is there a way to use some sort of dynamic content? I use JS to at least show and download the latest available package without having to update the web site.

see: https://github.com/tessus/mod_authnz_ibmdb2/blob/gh-pages/index.html#L17-L37

Here are a few questions:

- why is the zip file located in the assets directory of the web site?
    Wouldn't it make more sense to add this binary to the corresponding release ?
-    is there a way to create dynamic content (e.g. the SRI hash) for a release? (otherwise the web site has to be updated every time there's a release)

I create the SRI hash with openssl on the command line, but I doubt we have access to PHP or server side openssl to get something like this done on the github web site. So what's the best approach to handle this?
Is it possible to add the SRI hash to a file in the repo and read that file with JS?

**Comment by xuv** [comment]
Yes. All website is static and built with [Jekyll](https://jekyllrb.com/).
I don't think it's necessary to use dynamic content. But maybe I'm wrong. I'm not really sure I understand the example you showed.
Yes, the website is regenerated every time something changes. That's how Jekyll works.
I'm not really sure why loading dynamic content would be a better solution. Because adding new icons means generating new documentation, zip files, js, etc... So there needs to be some regeneration. anyway.

As for your question:

- Not sure what you mean by having the zip in the corresponding release. You mean pointing to the GH official repo releases? If, yes. That is probably the right way. We forked this website from Font Awesome . So they have done things a certain way. We are slowly changing it where we see a better way to do it. So you're welcome to improve the process.

- I've looked into how to generate a sha256 with Jekyll. I found 2 options: 
  - Here is how someone kinda way with a custom script. Though it uses SCSS and I have not managed to change it correctly yet. https://vcsjones.com/2016/11/02/sri-with-jekyll/
  - Or there is this more heavy plugin for asset management called [jekyll-assets](https://github.com/envygeeks/jekyll-assets). It does too much for our needs. But it does generate a file integrity sum. So we might be using that.

What do you think? Do you have some ruby knowledge and can craft a simple custom script? or we go for the second solution?

**Comment by tessus** [comment]
Ok, I have to look into jekyll. I'm not sure I understand the concept. 

In gh-pages there are only index.html files. So, if I wanted to change the web site, I would have to change the corresponding index.html file. So what is jekyll doing?

Yes, I know Ruby from Chef automation. But first I have to understand what Jekyll is really doing in the background, or if it is doing something at all. I don't see any rules or source files that jekyll would transform into html, so maybe I'm missing something here. Let me read up on it.

**Comment by xuv** [comment]
Jekyll turns a series of Markdown files and templates into a static website. 
Github can automatically deploy a set of .md files and templates and serve them as static website using Jekyll. But they are quite restrictive in terms of plugins you can use. And certainly can not use your own custom plugins. So the way we do it here is we have the webstie source files in 'master' and the building and deploying is done using [jgd](https://github.com/yegor256/jekyll-github-deploy) locally (wich builds the site and commits it to the 'gh-pages' branch). 

Github then serves whatever is commited in the 'gh-pages' branch.

**Comment by xuv** [comment]
But you can ignore that deploy part. You can test everything locally and see that the website is functioning properly. I can do the deploy later once you have commited your changes to `master` or into a `branch` I can review.

**Comment by tessus** [comment]
Thanks for the explanation. I will look into it. Cheers.

**Comment by tessus** [comment]
Ok, I've written the plugin and changed the `Get Started` page to include the CDN link. It works nicely.

Btw, I've noticed that the `View LESS` and `View SASS` links on the example page are wrong. I'll fix that too.

Do you want me to create a PR or can I commit the changes directly to master?

**Comment by xuv** [comment]
Go ahead. And push it to master. I have not figured out really how to do things properly in terms of collaboration. I think it will be nice at some point to have an organized way to submit contributions. But at this time and since you asked and warned me, you can go ahead.
