### ISSUE TITLE
Icon request: fa-zotero

### ISSUE THREAD

**Issue by qwertygc** [ForkAwesome/Fork-Awesome#42]
Hi!
[Zotero](https://www.zotero.org/) is a personnal research assistant, using for collect, cite, and share research. The [icon](https://www.zotero.org/static/images/theme/zotero_theme/zotero_128.png).

Regards

**Comment by xuv** [comment]
Hey. Nice project this Zotero app. I did not know about it.
Could you describe a use case for a Zotero icon in the Fork Awesome set.
What is the problem you are trying to solve?
How would someone use the Zotero icon?
Thx.

**Comment by qwertygc** [comment]
Zotero have a social network option. I would like put the zotero icon, in my website, for show my academic profile on the zotero website.
Regards

Le 27 février 2018 19:20:03 CET, Julien Deswaef <notifications@github.com> a écrit :
>Hey. Nice project this Zotero app. I did not know about it.
>Could you describe a use case for a Zotero icon in the Fork Awesome
>set.
>What is the problem you are trying to solve?
>How would someone use the Zotero icon?
>Thx.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ForkAwesome/Fork-Awesome/issues/42#issuecomment-368975445

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by xuv** [comment]
Ok. Thanks for the explanation.

**Comment by xuv** [comment]
@qwertygc I understand the request and the problem you are trying to solve. But it seems to me the branding of Zotero is quite different from the logo you are pointing to. If I search their website, I don't find anything that resembles that. Instead, I see this logo: https://www.zotero.org/static/images/bs4theme/zotero-logo.svg Which is quite different. 

We could use that as an icon, but I doubt it really has the effect you are looking for. It's not really an icon. The 'Z' seems to be the only thing that could function as an icon. But it's mostly due to its color. Once you turn it to black and white. I'm not sure this will be recognizable.

In fact the only occurence of that other logo you point to is on their github profile: @zotero  But is that still a thing? Or just something they forgot to update?

**Comment by xuv** [comment]
Ok. Though, I really don't understand why don't they don't use it on their website?
Am I missing something? 
You can for sure draw it in SVG. That would be nice.
But maybe it would be nice to invite someone from @zotero in this discussion. Don't you think. Just to have their opinion on this matter. Os is there already a discussion somewhere about this?

**Comment by qwertygc** [comment]
Yes, we can invite @zotero in this discussion.

**Comment by xuv** [comment]
Do you know any people from that organization we could invite here. I'm not sure they will receive notifications even if we tag the org name in this issue. (Probably a Github mechanism to prevent spam from issues you have not expressly asked to watch)

**Comment by qwertygc** [comment]
No sorry !

**Comment by qwertygc** [comment]
I have made a svg file if you want.
[zotero.svg.txt](https://github.com/ForkAwesome/Fork-Awesome/files/1770750/zotero.svg.txt)

**Comment by xuv** [comment]
Nice work and thanks for finding the Zotero branding page. Now indeed it all make sense. They do have a complete different design between the logo and the icon.

I see that their icon, at the smallest side, does not have a 'boxed' background.  ![zotero_16x16x32](https://user-images.githubusercontent.com/192539/36850834-c085902e-1d35-11e8-8bcd-013e0be385b3.png) Would that be something we should be considering? What is your opinion on this?

Because as you have experienced in turning their design into a flat black and white icon, it's not an easy thing to do to stay true to the original design.

**Comment by xuv** [comment]
Ok, I've taken your icon proposition and worked from there. I've mainly added some depth to the Z and tried to different approaches with the outline (1) or  infill (2).

<img width="338" alt="screen shot 2018-03-01 at 10 58 00" src="https://user-images.githubusercontent.com/192539/36854627-73443626-1d3f-11e8-8faa-2b899c56522b.png">

We definitely should get the input from one of the @zotero people here.

**Comment by micahilbery** [comment]
I like 2. I think it works best with the rest of the icon set.

**Comment by qwertygc** [comment]
I like also 2.

**Comment by qwertygc** [comment]
What's new ? We include the zotero's icon ?

**Comment by xuv** [comment]
@qwertygc Yes, the issue is pretty dead on their side. No response at all.

**Comment by qwertygc** [comment]
OK. We include the logo #2 ?

**Comment by xuv** [comment]
Sure. Might need a little more padding inside the hexagon... I think. Just a few pixels though.

**Comment by xuv** [comment]
@qwertygc Do you feel comfortable enough with Inkscape, SVG and Git to follow this process: https://github.com/ForkAwesome/Fork-Awesome/blob/master/CONTRIBUTING.md#adding-a-new-icon ?

**Comment by qwertygc** [comment]
For inkscape, no problem. For git, a little bit.

**Comment by qwertygc** [comment]
Think you :-)

**Comment by huachuman** [comment]
> @qwertygc Yes, the issue is pretty dead on their side. No response at all.

This is standard for the zotero team... way too many users for how many developers they have. Those guys should hire people. It's embarrassing how slow their progress is considering a gigantic portion of the developed world relies on it for academic research.
