### ISSUE TITLE
Icon request: icon-fedora

### ISSUE THREAD

**Issue by gergelypolonkai** [ForkAwesome/Fork-Awesome#78]
I noticed there is an icon for Debian, but other major distros are missing. Being a long time Fedora user I thought I chime in with this request.

I’m no font editor by any means, but in case it helps, here is a link to an [SVG version of their logo](https://commons.m.wikimedia.org/wiki/File:Fedora_logo.svg).

**Comment by tessus** [comment]
I like the idea, but this logo might be a bit complicated. 

The icon in the font can only be one color. So the dark blue would be black and the white f would be removed. So that's not an issue, but what do you do with the light blue part (the one that creates an infinity symbol when combined with the f)? If you remove that part, it's not their logo anymore.

**Comment by gergelypolonkai** [comment]
What if the outer shape is not black, just a thin line? I that case the f shape can be black, and the rest may be white with a thin line around. Although I don’t know how it would look like with a small font size…

**Comment by bochecha** [comment]
In the original FontAwesome issue, @mattdm (the current Fedora Project Leader) and @mairin (the Fedora Design Team lead) made some proposals:

https://pagure.io/design/issue/539

@mattdm, @mairin: hi, now you know about this repo. :slightly_smiling_face:

**Comment by xuv** [comment]
I would tend to follow @mairin's feeling in the issue linked here. About the checkered icon, she says (emphasisi are mine):

> [...] This icon should not be used in print and it should not be used in any other non-font icon treatment (this is why **I am less than enthusiastic about addressing this issue at all**, I'm concerned about the floodgates it may open.)

Since she is in charge of design at Fedora and since we can not guarantee how ForkAwesome would be used, I tend to agree with her and would say that in this particular case, it's safer not to include thee Fedora logo in the list of symbols.

**Comment by tessus** [comment]
In this case I suggest we create a wiki page and/or add it to the web site (e.g. let's call it `Wall of Shame`) where we list all companies that explicitly forbid their icon or logo to be added to the ForkAwesome font.

We can then direct people to that page, when an icon request for such an icon is created.

Apart from the fact that I personally think that a company disallowing the use of its logo is not only stupid but could poentially hurt the brand, it is their choice after all and we have to respect that. Having said that we should still list those somewhere.

**Comment by xuv** [comment]
I would tend not to put a wall of shame. This could misinterpreted. We might not always know or have the complete picture on why things happen in a way or in another. Things are not always black and white. And I don't see really the good it would do. This is touching on logos, trademarks and thus identity. We should not "shame" anyone because of this.

**Comment by tessus** [comment]
Just to clarify:

The name Wall of Shame was rather a joke (do you see the _e.g._ in front of the sentence?).
However, the page for listing icons that we can't add to the font was not.

**Comment by xuv** [comment]
@tessus Sorry for the misinterpretation. Indeed, I saw the e.g. which I interpreted literally. 

I'm agreeing with you and @gergelypolonkai on a documentation page that explains why this or that icon is not inserted. Something to put on the TODO list.

**Comment by tessus** [comment]
> documentation page that explains why this or that icon is not inserted.

The question is how do we do that?

- markdown document in the repo?
- part of the web site?
- use a project wiki page?

**Comment by tessus** [comment]
Let's move this discussion to #80
