### ISSUE TITLE
Icon request: fa-basketball

### ISSUE THREAD

**Issue by iamcryptoki** [ForkAwesome/Fork-Awesome#87]
Hi,

I think it would be fantastic to have an icon for "Basketball".

Example : 

![46341-basketball-ball-outline](https://user-images.githubusercontent.com/22425397/41218473-7f25c484-6d5b-11e8-8835-7e5453925316.png)

More examples [here](http://freevector.co/tag/basketball).

**Comment by tessus** [comment]
Can you please describe a use case for this icon?

**Comment by iamcryptoki** [comment]
Can you please describe a use case for the existing fa-futbol-o icon?

![soccer-icon](https://user-images.githubusercontent.com/22425397/41289252-7860fcd8-6e49-11e8-962a-052ebf6987fc.jpg)

**Comment by tessus** [comment]
No, I can't because I didn't add this icon.

However, if you want an icon to be added, you should add a use case. If you don't have one, you don't need the icon. Adding icons makes the font bigger. So, if there's no use case why should it be added in the first place?

@xuvI think it is time to add a template for icon requests. I have a few in a test repo. github also allows different templates for different purposes. let's talk about this offline.

**Comment by xuv** [comment]
Hey. I think both of your questions are legitimate. Indeed, from @iamcryptoki's point of view, I understand the request and I also agree that if there is a _Futbal_ icon, there could be a basketball one or a baseball one. But if you, @iamcryptoki, don't have an immediate use for it at the moment that you can share with us, then it's not probably going to be on our priority list. 

On another hand, I also appreciate that you linked to a usable icon. There is probably some work to do on it to get the line width in balance with the rest of the line width used in the other icons. But it's a good proposition to start from. 

As @tessus suggested also, having a template for icon requests will help in the future ask for these questions from the start.
